spring.application.name=rifugio
spring.datasource.url=jdbc:h2:file:./data/rifugio
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=embedded

# con create, viene sempre sovrascritto
# con create-drop, viene sovrascritto solo al primo avvio
# con udate, ogni volta che viene effettuata una modifica al modello, viene aggiornata la struttura del database